### ISSUE TITLE
Deploying behind Traefik Reverse Proxy

### ISSUE THREAD

**Issue by le-patenteux** [benjaminbear/docker-ddns-server#12]
Hello, if ever you can provide information on how to deploy this container, with docker-compose, behind traefik, that would be incredible!

Also, is the webUI also on 8080 or is it on another port? because I can't reach it.

**Comment by benjaminbear** [comment]
adding those labels and networks to your ddns compose file
```
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=webproxy"
      - "traefik.http.services.ddns.loadbalancer.server.port=8080"
      - "traefik.http.services.ddns.loadbalancer.server.scheme=http"
      - "traefik.http.routers.ddns.rule=Host(`dyn.${DOMAIN}`)"
      - "traefik.http.routers.ddns.entrypoints=websecure"
      - "traefik.http.routers.ddns.tls.certresolver=myresolver"
      - "traefik.tcp.routers.ddns.entrypoints=dns"
      - "traefik.tcp.routers.ddns.rule=HostSNI(`dyn.${DOMAIN}`)"
      - "traefik.tcp.routers.ddns.service=ddns"
      - "traefik.tcp.services.ddns.loadbalancer.server.port=53"
      - "traefik.udp.routers.ddns.entrypoints=dns-udp"
      - "traefik.udp.routers.ddns.service=ddns"
      - "traefik.udp.services.ddns.loadbalancer.server.port=53"
    networks:
      - webproxy
      - default

networks:
  webproxy:
    external: true
  default:
    driver: bridge
```

with traefik config like:
```  traefik:
    image: "traefik:v2.5.1"
    restart: always
    container_name: "traefik"
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.dns.address=:53/tcp"
      - "--entrypoints.dns-udp.address=:53/udp"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=yamail@bla.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--providers.file.directory=/conf"
    ports:
      - "80:80"
      - "443:443"
      - "53:53"
      - "53:53/udp"
    volumes:
      - "traefik/conf:/conf"
      - "traefik/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - webproxy

networks:
  webproxy:
    external: true```


should do it
