### ISSUE TITLE
Having trouble with DNS Setup

### ISSUE THREAD

**Issue by mirisbowring** [benjaminbear/docker-ddns-server#14]
Hi,
i've deployed the container and opened the 53 Port in my Firewall.

I've created an CNAME record on my Domain for ddns.domain.tld. This points to my nginx which is a reverse proxy with TLS offloading for the UI (:8080).
I can access the UI with the BASIC Auth credentials, and API Requests are working too.

I also added Following DNS Records:
| Host | Type | Destination | Description |
| --- | --- | --- | --- |
| ddns | A | 123.123.123.123 | points to nginx reverse proxy with TLS offloading |
| ... | ... | ... | ... |
|  myzone | NS | mzns1 | |
| mzns1 | A | 123.123.123.123 | |
| mzns1 | AAAA | ab:00:::03 | |

The host was refreshed successfully via API (i see it in Logs and on UI)

**my problem is:**
When i enter https://host.myzone.domain.tld , i cannot reach my server. I am getting the following error:

Hmmm… can't reach this page

```
It looks like the webpage at https://host.myzone.domain.tld/ might be having issues, or it may have moved permanently to a new web address.
ERR_TUNNEL_CONNECTION_FAILED
```

I enabled Port Forwarding on my Router already. When entering https://Router-IP, I can access my Server behind it.

Somehow it seems, that the NS Record is not really propageted, because i cannot even ping my URL except using a custom DNS:

```
$ ping host.myzone.domain.tld

ping: host.myzone.domain.tld: Temporary failure in name resolution

$ nslookup host.myzone.domain.tld

Server:         127.0.0.53
Address:        127.0.0.53#53
 
** server can't find host.myzone.domain.tld: SERVFAIL
 
$ nslookup host.myzone.domain.tld myzone.domain.tld

nslookup: couldn't get address for 'myzone.domain.tld': failure

$ nslookup host.myzone.domain.tld mzns1.domain.tld

Server:         mzns1.domain.tld
Address:        123.123.123.123#53
 
Name:   host.myzone.domain.tld
Address: <router-ip>
```

It's been already 2 Days since i configured the DNS.
What am i doing wrong?

**Comment by w3K-one** [comment]
I'm having a little difficulty following your setup, so I'll give you a run-down of _my_ setup and maybe it can help you resolve your issue.

To begin with, it is important to know that NameServer names should ideally be officially registered for what will become your (D)DNS Server. This registration is typically done through your domain registrar. Under GoDaddy, for example, you would create a "hostname" or "hostnames" for any nameserver names you wish to use. Depending on your registrar, you may have to contact support to have them create these for you.

With the known risk of drawing unwanted attention to my server, I will use the actual real-world info to elaborate my particular scenario.

The domain I use for my DDNS_DOMAIN is DVR.BZ (it's for my video surveillance clients, so very appropriate in this case). The nameserver (DDNS_PARENT_NS) for DVR.BZ is **Furia.w3K.co**. The nameserver hostname was registered on GoDaddy (my registrar for W3K.CO domain) using their hostname feature (I included screenshots) and was set to the same IP of the server running the **docker-ddns-server** container (**99.92.184.105**).
![NS1](https://user-images.githubusercontent.com/17402207/171316509-059474ce-69f4-4540-8db7-b9d74c80c192.png)
![NS2](https://user-images.githubusercontent.com/17402207/171316510-1ef25e47-e556-44a7-b25a-a28e4320d5e5.png)

I also created **A record** for the same Hostname I registered (**furia.w3k.co**) and pointed it to the same **99.92.184.105** IP address. This was created on CloudFlare, my DNS Host for W3K.CO - which goes to show you do NOT need to have your DNS hosted by your registrar for this to work.
![NS3](https://user-images.githubusercontent.com/17402207/171324148-d858b0e2-c4f6-4f48-96cf-767922f4914d.png)

I deploy DOCKER-DDNS-SERVER stack with the following compose:
```
version: '3'

volumes:
  bind-data:
  database:

services:
  ddns:
    image: bbaerthlein/docker-ddns-server:latest
    container_name: ddns
    restart: unless-stopped
    environment:
      DDNS_TITLE: 'w3K DDNS'
      DDNS_ADMIN_LOGIN: '😉:😈'
      DDNS_DOMAINS: 'dvr.bz'
      DDNS_PARENT_NS: 'furia.w3k.co'
      DDNS_DEFAULT_TTL: '600'
      DDNS_CLEAR_LOG_INTERVAL: '600'
      DDNS_ALLOW_WILDCARD: 'TRUE'
      DDNS_LOGOUT_URL: 'https://w3K.domains'
    ports:
      - "8080:8080"
      - "53:53"
      - "53:53/udp"
    volumes:
       - bind-data:/var/cache/bind
       - database:/root/database

```
I then access my DOCKER-DDNS-SERVER instance on port 8080, I create record for www.dvr.bz then I proceed to my server's docker volume folder... most likely _/var/lib/docker/volumes_ where I locate my ddns_bind-data folder, I manually edit my **dvr.bz.zone** file to setup A record for @ (DVR.BZ) pointing to 99.92.184.105, save it and restart the container. Now that DVR.BZ resolves to the same IP, I use my NGINX Proxy setup to add SSL and provide access to my instance on https://dvr.bz

I hope my explanation wasn't too convoluted and that by providing the actual domain and ip info, it makes it easier to follow and understand my setup (which works) as opposed to yours.
