### ISSUE TITLE
disable auth

### ISSUE THREAD

**Issue by maltegrosse** [benjaminbear/docker-ddns-server#16]
disable auth would be a nice feature in order to plugin some oauth proxy in front of the ui.

perhaps some minor changes have to be done:
either here:
https://github.com/benjaminbear/docker-ddns-server/blob/master/dyndns/handler/handler.go#L69
something like os.Getenv("DDNS_ADMIN_DISABLE") --> return true

or here:
https://github.com/benjaminbear/docker-ddns-server/blob/master/dyndns/handler/handler.go#L90
just allow empty admin env variable (not sure how it behause in the auth process if ein empty string is set....)

PS. moving all admin routes in an admin subfolder would make to regex matching easier for the oauth proxy, something like ./admin/. and redirect all ./  to ./admin/

**Comment by benjaminbear** [comment]
I think this is a good idea, will add that feature.

**Comment by maltegrosse** [comment]
successful deployed this ddns server with my latest PR behind oauth2 proxy:
(disclaimer: the yml files/deployments are not yet optimized, but was quite a mess to get it somehow working... lets see it as a **proof-of-concept**)

setup:
- keycloak 17.x
- traefik 2.7 rc2
- oauth 7.2.1

add openid client at keycloak with secret etc.. point the dns setting to your vps etc...
```
A -> ns.example.com -> VPS IP
NS-> dns.example.com -> ns
```

traefik.yml:
```
log:
  level: INFO
defaultEntryPoints:
  - websecure
entryPoints:
  web:
    address: ":80"
    forwardedHeaders:
      insecure: true
  websecure:
    address: ":443"
    forwardedHeaders:
      insecure: true
  dns:
    address: ":53/tcp"
  dns-udp:
    address: ":53/udp"
api:
  insecure: true
  dashboard: true
serversTransport:
  insecureSkipVerify: true
certificatesResolvers:
  le:
    acme:
      email: admin@example.com
      storage: /etc/traefik/acme.json
#      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web
providers:
  docker:
    exposedByDefault: false
    watch: true
  file:
    filename: /etc/traefik/services.yml
    watch: true
```

traefik-services.yml
```
http:
  middlewares:
    auth-headers:
      headers:
#        sslRedirect: true
        stsSeconds: 315360000
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
 #       sslHost: example.com
        stsIncludeSubdomains: true
        stsPreload: true
        frameDeny: true
    oauth-auth:
      forwardAuth:
        address: https://oauth.dns.example.com/oauth2/auth_or_start
        trustForwardHeader: true
        authResponseHeaders:
          - X-Auth-Request-Access-Token
          - Authorization
          - X-Auth-Request-User
          - X-Auth-Request-Email
          - Set-Cookie
    oauth-errors:
      errors:
        status:
          - "401-403"
        service: oauth@docker
        query: "/oauth2/auth_or_start"
       # passHostHeader: false
```

docker-compose.yml
```
version: '3.5'
services:
  traefik:
    image: "traefik:v2.7"
    restart: always
    container_name: "traefik"
    environment:
      TZ: 'Europe/Berlin'
    command:
      - "--providers.docker=true"
      - "--providers.docker.watch=true"
      - "--providers.file=true"
      - "--providers.file.watch=true"
    ports:
      - "8080:8080"
      - "80:80"
      - "443:443"
      - "53:53"
      - "53:53/udp"
    volumes:
      - "./traefik.yml:/etc/traefik/traefik.yml"
      - "./traefik-services.yml:/etc/traefik/services.yml"
      - ./acme.json:/etc/traefik/acme.json
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - ext
  oauth:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.2.1
    hostname: oauth
    container_name: oauth
    restart: unless-stopped
    depends_on:
      - ddns
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.oauth.middlewares=auth-headers@file"
      - "traefik.http.routers.oauth.entrypoints=websecure"
      - "traefik.http.routers.oauth.rule=Host(`oauth.dns.example.com`) || PathPrefix(`/oauth2/`)"
      - "traefik.http.routers.oauth.tls.certResolver=le"
      - "traefik.http.routers.oauth.service=oauth"
      - "traefik.docker.network=traefik_default"
      - "traefik.http.services.oauth.loadbalancer.server.port=4180"
    environment:
      TZ: 'Europe/Berlin'
      OAUTH2_PROXY_CLIENT_ID: 'dyndns'
      # keycloak needs a slash in front of the groups (make sure the client 1. group exists and 2. the user assigned->otherwise oauth erros) 
      OAUTH2_PROXY_ALLOWED_GROUPS: '/some-group'
      OAUTH2_PROXY_CLIENT_SECRET: 'whateversecretkcprovided'
      OAUTH2_PROXY_COOKIE_DOMAINS: '.example.com'
      OAUTH2_PROXY_COOKIE_REFRESH: '1h'
      OAUTH2_PROXY_COOKIE_SECURE: 'true'
      OAUTH2_PROXY_COOKIE_SECRET: 'generatesomesecret'
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_EMAIL_DOMAIN: '*'
      OAUTH2_PROXY_FOOTER: '-'
      OAUTH2_PROXY_HTTP_ADDRESS: '0.0.0.0:4180'
      # keycloak needs this
      OAUTH2_PROXY_UPSTREAMS: 'static://202'
      OAUTH2_PROXY_PASS_BASIC_AUTH: 'false'
      OAUTH2_PROXY_PASS_USER_HEADERS: 'true'
      OAUTH2_PASS_AUTHORIZATION_HEADER: 'true'
      OAUTH2_PROXY_PROVIDER: 'oidc'
      OAUTH2_PROXY_PROVIDER_DISPLAY_NAME: 'keycloak'
      OAUTH2_PROXY_REDIRECT_URL: 'https://oauth.dns.examplecom/oauth2/callback'
      #keycloak oidc url
      OAUTH2_PROXY_OIDC_ISSUER_URL: 'https://auth.example.com/realms/example'
      OAUTH2_PROXY_REVERSE_PROXY: 'true'
      OAUTH2_PROXY_SET_AUTHORIZATION_HEADER: 'true'
      OAUTH2_PROXY_SET_XAUTHREQUEST: 'true'
      OAUTH2_PROXY_WHITELIST_DOMAINS: '.example.com'
      OAUTH2_PROXY_WHITELIST_DOMAIN: '.example.com'
      OAUTH2_PROXY_COOKIE_DOMAINS: '.example.com'
      # without this keycloak does not redirect after successful login
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: 'true'
    networks:
      - ext
    ports:
      - "4180:4180"
  ddns:
    # switch to benjamins container once merged and pushed
    image: maltegrosse/docker-ddns-server:1.0.1
    container_name: "dyndns"
    depends_on:
      - traefik
    restart: always
    environment:
# remove login
#      DDNS_ADMIN_LOGIN: ''
      DDNS_DOMAINS: 'dns.example.com'
      DDNS_PARENT_NS: 'ns.example.com'
      DDNS_DEFAULT_TTL: '3600'
      DDNS_TITLE: 'example dyndns'
      DDNS_CLEAR_LOG_INTERVAL: '30'
      DDNS_ALLOW_WILDCARD: 'true'
      # provide a custom logout url from your oidc provider
      DDNS_LOGOUT_URL: 'https://oauth.dns.example.com/oauth2/sign_out?rd=https%3A%2F%2Fexample.com'
      TZ: 'Europe/Berlin'
    volumes:
       - ./dyndns/bind-data:/var/cache/bind
       - ./dyndns/database:/root/database
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_default"
      - "traefik.http.services.ddns.loadbalancer.server.port=8080"
      - "traefik.http.services.ddns.loadbalancer.server.scheme=http"
      - "traefik.http.routers.ddns.rule=Host(`dns.example.com`)"
      - "traefik.http.routers.ddns.entrypoints=websecure"
      - "traefik.http.routers.ddns.tls.certresolver=le"
      - "traefik.http.routers.ddns.middlewares=oauth-errors@file,oauth-auth@file"
      # run all other endpoints without openid auth (basic auth enabled)
      - "traefik.http.routers.ddns-no-auth1.rule=Host(`dns.example.com`)  && PathPrefix(`/update`)"
      - "traefik.http.routers.ddns-no-auth1.entrypoints=websecure"
      - "traefik.http.routers.ddns-no-auth1.tls.certresolver=le"
      - "traefik.http.routers.ddns-no-auth2.rule=Host(`dns.example.com`)  && PathPrefix(`/nic`)"
      - "traefik.http.routers.ddns-no-auth2.entrypoints=websecure"
      - "traefik.http.routers.ddns-no-auth2.tls.certresolver=le"
      - "traefik.http.routers.ddns-no-auth3.rule=Host(`dns.example.com`)  && PathPrefix(`/ping`)"
      - "traefik.http.routers.ddns-no-auth3.entrypoints=websecure"
      - "traefik.http.routers.ddns-no-auth3.tls.certresolver=le"
      # based on benjamins solution
      - "traefik.tcp.routers.ddns.entrypoints=dns"
      - "traefik.tcp.routers.ddns.rule=HostSNI(`dns.example.com`)"
      - "traefik.tcp.routers.ddns.tls.passthrough=true"
      - "traefik.tcp.routers.ddns.service=ddns"
      - "traefik.tcp.services.ddns.loadbalancer.server.port=53"
      - "traefik.udp.routers.ddns.entrypoints=dns-udp"
      - "traefik.udp.routers.ddns.service=ddns"
      - "traefik.udp.services.ddns.loadbalancer.server.port=53"
    networks:
      - ext
networks:
  ext:
    name: traefik_default
    external: true
