### ISSUE TITLE
Configuration with NGINX Proxy Manager [Reverse Proxy]

### ISSUE THREAD

**Issue by empx92** [benjaminbear/docker-ddns-server#38]
i have the follwing configuration in my docker

```
version: '3'
services:
  ddns:
    image: bbaerthlein/docker-ddns-server:latest
    container_name: dyndns
    restart: unless-stopped
    environment:
      DDNS_ADMIN_LOGIN: 'example:example_pwd'
      DDNS_DOMAINS: 'ns.example.com'
      DDNS_PARENT_NS: 'ns.example.com'
      DDNS_DEFAULT_TTL: '3600'
    ports:
      - "53:53"
      - "53:53/udp"
      - "8080:8080"
    volumes:
       - ./bind-data:/var/cache/bind
       - ./database:/root/database
    networks:
       - proxy
       - dyndns
networks:
  dyndns:
  proxy:
    external: true 
```

The configuration works fine and is running. I also can update the IPs but i couldn't manage to get the answer when calling the host.

Configuration DNS Try 1:
1.) ns.example.com  A IP-OF-NGINX-PROXY
2.) *.ns.example com CNAME ns.example.com
>>>Not working (only for update)

Configuration DNS Try 1:
1.) ns.example.com  A IP-OF-NGINX-PROXY
2.) *.ns.example com NS ns.example.com
>>>Not working (only for update), if i try the host host1.ns.example.com i get "no dns-adress found. DNS_PROBE_POSSIBLE " when i look at the terminal of DDNS-Server there is also no request.

If i make a NS-Lookup at ns.example.com there are even no entries

So i am wondering if i have some misconfiguration of my NGINX Proxymanager.
Did anyone manage it to get it work?
